apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hcm-demo-demo-appset-frontend
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: workbench-ui
          - name: digit-ui
          - name: dashboard-ui
          - name: payments-ui
          - name: core-ui
          - name: console
          - name: microplan-ui

  template:
    metadata:
      name: 'demo-{{name}}'

    spec:
      project: demo-project

      source:
        repoURL: git@github.com:egovernments/health-campaign-devops.git
        targetRevision: azure-install-hcm-demo
        path: config-as-code/helm/charts/frontend/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../../environments/demo-tenant.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: demo

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
