apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.name" . }}-clamd
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  clamd.conf: |
{{- range $key, $value := .Values.clamdConfigDict }}
  {{- if kindIs "slice" $value }}
    {{- range $value }}
    {{ $key }} {{ . }}
    {{- end }}
  {{- else }}
    {{ $key }} {{ $value }}
  {{- end }}
{{- end }}