cluster-configs:
    secrets:

        sso:
            auth-sso-default-password-override-tg-oidc-azure: ENC[AES256_GCM,data:2OuPvVilVkTd,iv:6HwIOFrJlBOhMreAFHlTrvTHcx9w1rEIUTtN5X9GQwU=,tag:JxA4dBeZXg+bjHXSdBMD7w==,type:str]
            auth-user-default-password: ENC[AES256_GCM,data:Mj2p+udgTa0l,iv:vDez1uyavxzXBLhTJoiktMc1FJak6hfdPLRG4/0Gw0s=,tag:pBR2scIw/dUGLhVKBM2d+w==,type:str]
            graph-client-secret-tg-oidc-azure: ENC[AES256_GCM,data:5DIQjO3J0NSOK6hihkQmYz5Qx255lkXzKrAqYIOuaV6VK2mygI/XTA==,iv:S6S2P2AfzTixlIZsoq9scHwJykIwdASe9d/OjNELVQM=,tag:aM3x8SO+1e3rSsz7UdIk6g==,type:str]
