# Common Labels
labels:
  app: "excel-ingestion"
  group: "health"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "excel-ingestion"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "excel_ingestion_flyway_history"
    image:
      repository: "excel-ingestion-db"

# Container Configs
image:
  repository: "excel-ingestion"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/excel-ingestion/health"
  readinessProbePath: "/excel-ingestion/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: "3072Mi"
cpu_limits: "500m"
heap: -Xms256m -Xmx2048m
java-args: ""
egov-mdms-service-host-key: "mdms-v2"
egov-mdms-service-endpoint-key: "mdms-v2/v2/_search"
defaultLocale: "en_MZ"
java-enable-debug: false
java-debug-port: 5005

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: {{ index .Values "group-id" | default "excel-ingestion" }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: "/excel-ingestion"
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_CAMPAIGN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "project-factory-host" | default "project-factory" | quote }}
  - name: EGOV_HEALTH_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: individual
  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "egov-mdms-service-host-key" | quote }}
  - name: EGOV_ATTENDANCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-attendance
  - name: EGOV_ATTENDANCE_REGISTER_SEARCH_PATH
    value: health-attendance/v1/_search
  - name: EGOV_CAMPAIGN_DATA_SEARCH_PATH
    value: "project-factory/v1/data/campaign/_search"
  - name: EGOV_CAMPAIGN_CRYPTO_BULK_DECRYPT_PATH
    value: "project-factory/v1/crypto/_bulkDecrypt"
  - name: EGOV_HEALTH_INDIVIDUAL_SEARCH_PATH
    value: "individual/v1/_search"
  - name: EGOV_HIERARCHY_SEARCH_URL
    value: "boundary-service/boundary-hierarchy-definition/_search"
  - name: EGOV_BOUNDARY_RELATIONSHIP_SEARCH_URL
    value: "boundary-service/boundary-relationships/_search"
  - name: EGOV_FACILITY_SEARCH_PATH
    value: "facility/v1/_search"
  - name: EGOV_FILESTORE_UPLOAD_ENDPOINT
    value: "filestore/v1/files"
  - name: EGOV_FILESTORE_URL_ENDPOINT
    value: "filestore/v1/files/url"
  - name: EGOV_LOCALIZATION_SEARCH_PATH
    value: "localization/messages/v1/_search"
  - name: EGOV_MDMS_SEARCH_PATH
    value: {{ index .Values "egov-mdms-service-endpoint-key" | quote }}
  - name: DEFAULT_LOCALE
    value: {{ index .Values "defaultLocale" | quote }}
  - name: MANAGEMENT_HEALTH_REDIS_ENABLED
    value: "false"
  # JPA/Hibernate Configuration
  - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: "update"
  - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
    value: "org.hibernate.dialect.PostgreSQLDialect"
  - name: EXCEL_INGESTION_GENERATION_SAVE_TOPIC
    value: {{ index .Values "excel-ingestion-generation-save-topic" | default "save-generated-file" | quote }}
  - name: EXCEL_INGESTION_GENERATION_UPDATE_TOPIC
    value: {{ index .Values "excel-ingestion-generation-update-topic" | default "update-generated-file" | quote }}
  - name: EXCEL_INGESTION_PROCESSING_SAVE_TOPIC
    value: {{ index .Values "excel-ingestion-processing-save-topic" | default "save-processing-file" | quote }}
  - name: EXCEL_INGESTION_PROCESSING_UPDATE_TOPIC
    value: {{ index .Values "excel-ingestion-processing-update-topic" | default "update-processing-file" | quote }}
  - name: EXCEL_INGESTION_SHEET_DATA_SAVE_TOPIC
    value: {{ index .Values "excel-ingestion-sheet-data-save-topic" | default "save-sheet-data-temp" | quote }}
  - name: EXCEL_INGESTION_SHEET_DATA_DELETE_TOPIC
    value: {{ index .Values "excel-ingestion-sheet-data-delete-topic" | default "delete-sheet-data-temp" | quote }}
  - name: EXCEL_INGESTION_PROCESSING_RESULT_TOPIC
    value: {{ index .Values "excel-ingestion-processing-result-topic" | default "hcm-processing-result" | quote }}
