apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-configs-project
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:egovernments/health-campaign-devops.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'