{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dhis2-core-helm.fullname" . }}-postgresql-app
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ include "dhis2-core-helm.databaseUsername" . }}
  password: {{ include "dhis2-core-helm.databasePassword" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dhis2-core-helm.fullname" . }}-postgresql-superuser
  labels:
    {{- include "dhis2-core-helm.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ include "dhis2-core-helm.databasePassword" . }}
{{- end }}
