# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: environments/who-afro-hcm\-secrets\.yaml$
    azure_keyvault: 'https://who-afro-key-vault.vault.azure.net/keys/who-afro-key/2f8ab62d085c4b48a0ab018d28763874'
