# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: environments/dhis2\-secrets\.yaml$
    azure_keyvault: 'https://hcm-demo-kv.vault.azure.net/keys/sops-key/bd08e4ad057e40f790edcaae471b5959'
