apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: who-afro-egov-appset-business
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: egov-hrms
          - name: dashboard-ingest
          - name: dashboard-analytics

  template:
    metadata:
      name: 'egov-{{name}}'

    spec:
      project: egov-project

      source:
        repoURL: git@github.com:HCM-WHO-AFRO/health-campaign-devops.git
        targetRevision: azure-install-who-test
        path: config-as-code/helm/charts/business-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../../environments/who-afro-hcm.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '*'

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
