apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: who-afro-egov-appset-health
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: health-attendance
          - name: health-expense
          - name: health-muster-roll
          - name: boundary-management
          - name: project
          - name: stock
          - name: referralmanagement
          - name: product
          - name: individual
          - name: household
          - name: facility
          - name: beneficiary-idgen

  template:
    metadata:
      name: 'egov-{{name}}'

    spec:
      project: egov-project

      source:
        repoURL: git@github.com:HCM-WHO-AFRO/health-campaign-devops.git
        targetRevision: azure-install-who-test
        path: config-as-code/helm/charts/health-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../../environments/who-afro-hcm.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: '*'

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
