# Common Labels
labels:
  app: "digit-ui-mdms-v2"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui-mdms-v2"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "digit-ui"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui-mdms-v2/"
  readinessProbePath: "/digit-ui-mdms-v2/"

namespace: egov    
extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui-mdms-v2-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
