# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: environments/health-dev\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:218381940040:key/d83c3ae8-20df-418b-b8bb-5bdbe09e0f2c'
    pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

  - path_regex: environments/health-qa\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:218381940040:key/d83c3ae8-20df-418b-b8bb-5bdbe09e0f2c'
    pgp: 'B9FF61E01273EDF7DE298B52F4D6BD77E5C66196'

  - path_regex: environments/hcm-demo\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'

  - path_regex: environments/hcm-demo-latest\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'

  - path_regex: environments/hcm-demo-new\-secrets\.yaml$
    kms: 'arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2'

  - path_regex: environments/hcm-demo-azure\-secrets\.yaml$
    azure_keyvault: 'https://hcm-demo-kv.vault.azure.net/keys/sops-key/bd08e4ad057e40f790edcaae471b5959'

