loki:
  enabled: true
  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    common:
      path_prefix: /data/loki
      storage:
        azure:
          container_name: loki
          account_name: whoafrolokisaprd
          account_key: <AZURE_STORAGE_ACCOUNT_KEY> # Set via secret or environment variable
          use_managed_identity: false
          request_timeout: 0
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: "2023-10-20"
          store: tsdb
          object_store: azure
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      tsdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/index_cache
        shared_store: azure
        cache_ttl: 24h
      azure:
        container_name: loki
        account_name: whoafrolokisaprd
        account_key: <AZURE_STORAGE_ACCOUNT_KEY> # Set via secret or environment variable
        use_managed_identity: false
        request_timeout: 0
    compactor:
      working_directory: /data/loki/compactor
      shared_store: azure
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000
      retention_period: 720h
    ingester:
      wal:
        enabled: true
        dir: /data/loki/wal
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          replication_factor: 1
    memberlist:
      join_members:
        - loki-stack-memberlist
    analytics:
      reporting_enabled: false
  persistence:
    enabled: true
    size: 30Gi